### ISSUE TITLE
Isabelle/HOL gets stuck in OG_Hoare

### ISSUE THREAD

**Issue by kaizsv** [echronos/echronos-proofs#1]
The Isabelle/HOL is getting stuck while opening the file "EChronos_arm_sched_prop_bare_proof.thy". The Isabelle has run over 20 hours unchanged and always stucks at the 

> apply (blast dest: Basic_ntran rtrancl_imp_UN_relpow)

in OG_Hoare, however I can pass the OG_Hoare in original library of Isabelle without failure. I was wondering is there any requirement like more powerful machine or more time to pass the proof?

By the way, the version of my Isabelle/HOL is 2016.

![screenshot from 2017-06-12 11-24-42](https://user-images.githubusercontent.com/11775395/27018281-c2dc8aa0-4f61-11e7-8e20-72f16982a3f2.png)

**Comment by corlewis** [comment]
That definitely should not be taking so long to process. It appears that you are actually using Isabelle2016-1, which has just enough differences to Isabelle2016 that our proofs no longer processed. I've updated them and it should all work for you now.

**Comment by kaizsv** [comment]
Thank you for your help. I will use Isabelle2016 and try again.

**Comment by corlewis** [comment]
If you pull the latest commits then it should work with your current version of Isabelle.

**Comment by kaizsv** [comment]
Yes, I understand. I have passed all the proof with Isabelle2016-1.
